// types.js
export const FETCH_TAREFAS_REQUEST = 'FETCH_TAREFAS_REQUEST';
export const FETCH_TAREFAS_SUCCESS = 'FETCH_TAREFAS_SUCCESS';
export const FETCH_TAREFAS_FAILURE = 'FETCH_TAREFAS_FAILURE';

export const CREATE_TAREFA_REQUEST = 'CREATE_TAREFA_REQUEST';
export const CREATE_TAREFA_SUCCESS = 'CREATE_TAREFA_SUCCESS';
export const CREATE_TAREFA_FAILURE = 'CREATE_TAREFA_FAILURE';

export const UPDATE_TAREFA_REQUEST = 'UPDATE_TAREFA_REQUEST';
export const UPDATE_TAREFA_SUCCESS = 'UPDATE_TAREFA_SUCCESS';
export const UPDATE_TAREFA_FAILURE = 'UPDATE_TAREFA_FAILURE';

export const DELETE_TAREFA_REQUEST = 'DELETE_TAREFA_REQUEST';
export const DELETE_TAREFA_SUCCESS = 'DELETE_TAREFA_SUCCESS';
export const DELETE_TAREFA_FAILURE = 'DELETE_TAREFA_FAILURE';

export const COMPLETE_TAREFA_REQUEST = 'COMPLETE_TAREFA_REQUEST';
export const COMPLETE_TAREFA_SUCCESS = 'COMPLETE_TAREFA_SUCCESS';
export const COMPLETE_TAREFA_FAILURE = 'COMPLETE_TAREFA_FAILURE';

export const UPDATE_TAREFA_IMAGE_REQUEST = 'UPDATE_TAREFA_IMAGE_REQUEST';
export const UPDATE_TAREFA_IMAGE_SUCCESS = 'UPDATE_TAREFA_IMAGE_SUCCESS';
export const UPDATE_TAREFA_IMAGE_FAILURE = 'UPDATE_TAREFA_IMAGE_FAILURE';
